# Generated by Django 5.1.6 on 2025-03-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_session_id_category_image_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
