# Generated by Django 5.1.6 on 2025-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
